import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import USAMap from "react-usa-map"
import React from 'react'

export default function Home() {

  const [inputValue, setInputValue] = React.useState('Massachusetts')
  const [stateSucks, setStateSucks] = React.useState({})

  const mapHandler = (e) => {
    // e.preventDefault()
    // fetch('/api/politico', {
    //   method: 'get',
    //   headers: {
    //     'content-type': 'application/json',
    //   },
    // })
    //   .then((res) => res.json())
    //   .then((data) => {
    //     console.log(data)
    //   })
    alert('workin on it <3 kev')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Does my state suck?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          No
        </h1>
        <h4>Massachusetts does not suck. </h4>

        <p className={styles.description}>
       <small>Abortions are legal until 24 weeks. 
        The state Supreme Court has recognized a right to abortion 
        under the state Constitution. State law also protects abortion access.</small> 
        </p>
        <p>Tap a state to see if it sucks</p>
        <USAMap onClick={mapHandler} height={260} width={'100%'}/>
       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Data sourced from{' '}
          <span className={styles.logo}>
            <Image src="/POLITICOLOGO.svg" alt="Politico Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
